lib/spamzapper_web/router.ex
defmodule SpamzapperWeb.Router do
  use SpamzapperWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router,
    extensions: [PowResetPassword, PowEmailConfirmation]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :app_layout do
    plug :put_root_layout, html: {SpamzapperWeb.Layouts, :root}
  end

  pipeline :guest_layout do
    plug :put_layout, html: {SpamzapperWeb.Layouts, :guest}
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :admin do
    plug SpamzapperWeb.EnsureRolePlug, :admin
  end

  pipeline :moderator do
    plug SpamzapperWeb.EnsureRolePlug, [:moderator, :admin]
  end

  scope "/", Pow.Phoenix, as: "pow" do
    pipe_through [:browser, :protected, :app_layout]

    get "/registration/edit", RegistrationController, :edit
  end

  scope "/" do
    pipe_through [:browser, :guest_layout]

    pow_routes()
    pow_extension_routes()
  end

  scope "/", SpamzapperWeb do
    pipe_through [:browser, :protected, :moderator, :app_layout]

    live "/", PageLive, :index
  end

  scope "/", SpamzapperWeb do
    pipe_through [:browser, :protected, :moderator, :app_layout]

    get "/email-domains", EmailDomainController, :index
    get "/email-domains/:domain", EmailDomainController, :show
    post "/email-domains/:domain/ban", EmailDomainController, :create_ban
  end

  scope "/admin", SpamzapperWeb.Admin, as: :admin do
    pipe_through [:browser, :protected, :admin, :app_layout]

    resources "/members", MemberController
    resources "/users", UserController
  end

  # Other scopes may use custom stacks.
  # scope "/api", SpamzapperWeb do
  #   pipe_through :api
  # end

  # Enable LiveDashboard and Swoosh mailbox preview in development
  if Application.compile_env(:spamzapper, :dev_routes) do
    # If you want to use the LiveDashboard in production, you should put
    # it behind authentication and allow only admins to access it.
    # If your application does not have an admins-only section yet,
    # you can use Plug.BasicAuth to set up some basic authentication
    # as long as you are also using SSL (which you should anyway).
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through [:browser, :protected, :admin]

      live_dashboard "/dashboard", metrics: SpamzapperWeb.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/spamzapper_web/templates/layout/guest.html.eex
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    <title>Spamzapper</title>

    <link rel="stylesheet" crossorigin="anonymous"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" />
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />

    <%= csrf_meta_tag() %>
  </head>

  <body class="pow">
    <div class="container-fluid">
      <div class="row justify-content-md-center">
        <main role="main" class="col-md-6 pt-3 px-4">
          <div class="brand">
            <span>spam</span>zapper
          </div>
          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

          <%= @inner_content %>
        </main>
      </div>
    </div>
  </body>
</html>

lib/spamzapper_web/templates/layout/guest.html.heex
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    <.live_title>Spamzapper</.live_title>

    <link rel="stylesheet" crossorigin="anonymous"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" />
    <link rel="stylesheet" href={~p"/assets/app.css"} />

    <%= csrf_meta_tag() %>
  </head>

  <body class="pow">
    <div class="container-fluid">
      <div class="row justify-content-md-center">
        <main role="main" class="col-md-6 pt-3 pb-6 px-4">
          <div class="brand">
            <span>spam</span>zapper
          </div>
          <p class="alert alert-info" role="alert"><%= Phoenix.Flash.get(@flash, :info) %></p>
          <p class="alert alert-danger" role="alert"><%= Phoenix.Flash.get(@flash, :error) %></p>

          <%= @inner_content %>
        </main>
      </div>
    </div>
  </body>
</html>

lib/spamzapper_web/templates/layout/live.html.leex
<main role="main" class="col-md-9 col-lg-10 ml-sm-auto pt-3 px-4">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/spamzapper_web/templates/layout/root.html.leex
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <%= csrf_meta_tag() %>
    <%= if assigns[:page_title] do %>
      <%= live_title_tag assigns[:page_title], suffix: " · Spamzapper" %>
    <% else %>
      <%= live_title_tag "Spamzapper" %>
    <% end %>

    <link rel="stylesheet" crossorigin="anonymous"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" />

    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="">Spamzapper</a>

      <input class="form-control form-control-dark w-100"
             type="text" placeholder="Search" aria-label="Search" />

      <ul class="navbar-nav px-3">
        <%= render "usermenu.html", assigns %>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-3 col-lg-2 d-none d-md-block bg-light sidebar">
          <%= render "sidebar.html", assigns %>
        </nav>
        <%= @inner_content %>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" crossorigin="anonymous"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"></script>

    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>
  </body>
</html>

lib/spamzapper_web/templates/layout/sidebar.html.eex
<div class="sidebar-sticky">
  <ul class="nav flex-column">
    <li class="nav-item">
      <a class="nav-link" href="<%= Routes.page_path(@conn, :index) %>">
        <span data-feather="shield"></span>
        Dashboard
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= Routes.email_domain_path(@conn, :index) %>">
        <span data-feather="at-sign"></span>
        Email Domains
      </a>
    </li>

    <%= if @current_user.role == "admin" do %>
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Forum Admin</span>
      <a class="d-flex align-items-center text-muted" href="#">
        <span data-feather="plus-circle"></span>
      </a>
    </h6>
    <li class="nav-item">
      <a class="nav-link" href="<%= Routes.admin_member_path(@conn, :index) %>">
        <span data-feather="users"></span>
        Manage Members
      </a>
    </li>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Spamzapper Admin</span>
      <a class="d-flex align-items-center text-muted" href="#">
        <span data-feather="plus-circle"></span>
      </a>
    </h6>
    <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
      <li class="nav-item">
        <a class="nav-link" href="<%= Routes.live_dashboard_path(@conn, :home) %>" target="_blank">
          <span data-feather="activity"></span>
          Live Dashboard
        </a>
      </li>
    <% end %>
    <li class="nav-item">
      <a class="nav-link" href="<%= Routes.admin_user_path(@conn, :index) %>">
        <span data-feather="users"></span>
        Manage Users
      </a>
    </li>
    <% end %>
  </ul>
</div>

lib/spamzapper_web/templates/layout/usermenu.html.eex
<%= if @current_user do %>
  <li class="nav-item text-nowrap">
    <%= link @current_user.email, to: Routes.pow_registration_path(@conn, :edit),
      class: "nav-link" %>
  </li>
  <li class="nav-item text-nowrap px-3">
    <%= link "Sign out", to: Routes.pow_session_path(@conn, :delete),
      method: :delete, class: "nav-link" %>
  </li>
<% end %>